### ISSUE TITLE
【Compatibility-Windows】Problems in windows

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#265] opened 2023-08-11 09:01 UTC
1.[Overview]
In mac-arm64 package,overview page has more button ,but in win package,it has not this function.
In mac-arm64 package:
<img width="953" alt="截屏2023-08-11 16 40 07" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/ca8165d6-2ea5-4106-bb30-df8e80aca93f">

In win package:
<img width="1073" alt="截屏2023-08-11 16 40 39" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/832f28c1-f88c-4e3d-a056-a6b4be4c24ac">

2.[Receive]
In mac-arm64 package,address book does not overbold in receive page,but  in win package,it has.
In mac-arm64 package:
<img width="1326" alt="截屏2023-08-11 16 50 55" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/53479b8d-244b-463c-b225-9fa659e66df4">

In win package:
<img width="1337" alt="截屏2023-08-11 16 41 19" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/c5519164-470e-488b-9ac0-963cb9c0c0c0">

3.[Settings]:
A.In mac-arm64 package,system language shows "中文简体"  in default in settings page  ,but in win package,it shows abnormal.
B.In mac-arm64 package,default network tag shows ckb_testnet,but in win package,it shows ckb.
In mac-arm64 package:
<img width="1163" alt="截屏2023-08-11 16 55 02" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/675aaec2-0f4c-4423-9d1c-4623239a6b66">

In win package:
<img width="1084" alt="截屏2023-08-11 16 42 24" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/f3a57809-037a-4053-a365-f96cff60ebda">

**Comment by yanguoyu** [comment] 2023-08-11 09:08
> In mac-arm64 package,overview page has more button ,but in win package,it has not this function.
If you have more than 10 txs, it will show more, otherwise it will not show.

> In mac-arm64 package,address book does not overbold in receive page,but in win package,it has
IMO, it was caused by Windows display, but not Neuron.

> In mac-arm64 package,default network tag shows ckb_testnet,but in win package,it shows ckb.
Here tag depends on your ckb network type. mainnet -> ckb, testnet -> ckb_testnet, devnet -> ckb_dev

**Comment by yanguoyu** [comment] 2023-08-11 10:41
> In mac-arm64 package,system language shows "中文简体" in default in settings page ,but in win package,it shows abnormal.

Fixed by https://github.com/nervosnetwork/neuron/pull/2805#issuecomment-1674320870

**Comment by yanguoyu** [comment] 2023-08-14 06:58
Does this problem has fixed? @silySuper

**Comment by silySuper** [comment] 2023-08-14 08:26
Verified.

**Closed** 2024-04-29 08:17 UTC
Labels: bug
