### ISSUE TITLE
Problems with New UI-Nervos DAO

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#160] opened 2023-05-26 08:22 UTC
1.Same deposit amount，different  operations have different continue results.Firstly, **One can continue deposit，the other can not**.Secondly,on same amout,one shows insufficient balance，the other does not shows.
<img width="678" alt="截屏2023-05-26 14 52 02" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/c1afdfb6-6c0b-4529-94e7-305010c83999">
<img width="683" alt="截屏2023-05-26 14 53 03" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/0a10fe5f-8bdc-4c91-8da5-8c6876e17a26">

**The procedure is shown in the video：**

 https://github.com/Magickbase/neuron-public-issues/assets/25971273/cca2841e-6e01-40e7-ab04-7d815d849005

2.UI document need  chinese called "下一步",but this called “继续”, product manager may know this  small change.

<img width="701" alt="截屏2023-05-26 16 14 03" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/ff1de168-aa31-43d0-bb39-4524e0603669">

**Comment by WhiteMinds** [comment] 2023-05-29 09:28
> 1.Same deposit amount，different operations have different continue results.

This behavior is consistent with the logic of the old UI (production version), but I am unsure if it is reasonable.
For example, there is no prompt for `Slider` because it will never exceed the balance, whereas the prompt appears for `TextInput` because it involves manually entering a number that exceeds the balance.

> 2.UI document need chinese called "下一步",but this called “继续”, product manager may know this small change.

Confirmation from @Danie0918 is required.

**Comment by Danie0918** [comment] 2023-05-30 01:34
> > 1.Same deposit amount，different operations have different continue results.
> 
> This behavior is consistent with the logic of the old UI (production version), but I am unsure if it is reasonable. For example, there is no prompt for `Slider` because it will never exceed the balance, whereas the prompt appears for `TextInput` because it involves manually entering a number that exceeds the balance.
> 
> > 2.UI document need chinese called "下一步",but this called “继续”, product manager may know this small change.
> 
> Confirmation from @Danie0918 is required.

Regarding the copywriting, there will be no adjustments in this issue, and the UI is only used as a style reference.

**Comment by silySuper** [comment] 2023-05-30 01:38
OK

**Comment by WhiteMinds** [comment] 2023-05-30 08:08
> 1.Same deposit amount，different operations have different continue results.Firstly, One can continue deposit，the other can not.Secondly,on same amout,one shows insufficient balance，the other does not shows.

This issue has been fixed in the latest branch (tested and confirmed): https://github.com/nervosnetwork/neuron/pull/2688
Therefore, when the new-ui is merged into develop again, this problem will be automatically resolved. So, it can be ignored.

**Comment by yanguoyu** [comment] 2023-06-08 13:41
@silySuper  Develop has merged into new-ui branch, you can try it again with https://github.com/nervosnetwork/neuron/actions/runs/5194498526

**Comment by silySuper** [comment] 2023-06-16 08:45
verified

**Closed** 2024-04-29 08:17 UTC
Labels: bug
