### ISSUE TITLE
CKB process failed to restart during the shifting node

### ISSUE THREAD

**Issue by Cedar67** [Magickbase/neuron-public-issues#97] opened 2023-01-16 15:00 UTC
`testnet` is still displayed on the Neuron page after switching to `mainnet` in `Setting -> Data`

Reproduce version: develop branch and released v0.106.0 (Occasional appearance)

Locating cause: The ckb process failed to restart during the shifting node.

![image](https://user-images.githubusercontent.com/64718893/212686007-277d3404-0733-4206-972c-bc73086ddd16.png)

**Comment by yanguoyu** [comment] 2023-01-17 07:44
<img width="887" alt="image" src="https://user-images.githubusercontent.com/12881040/212836320-ec544a0a-fc9a-4b7f-9d0c-cd3bc28867fc.png">

I add print process close code when the `ckb` `close` event triggers.
I found that sometimes the `ckb` close code is 101(normal is null), it's not closed by `Neuron`, and it seems will relaunch later. So the relaunched process is out of `Neuron`'s control. Currently, the `ckb` variable is null, but the `ckb` is running. So we can't restart `ckb` node anymore.
I will try to find out why the `ckb` process closed with 101.

**Comment by Keith-CY** [comment] 2023-01-17 07:47
> <img alt="image" width="887" src="https://user-images.githubusercontent.com/12881040/212836320-ec544a0a-fc9a-4b7f-9d0c-cd3bc28867fc.png">
> 
> I add print process close code when the `ckb` `close` event triggers. I found that sometimes the `ckb` close code is 101(normal is null), it's not closed by `Neuron`, and it seems will relaunch later. So the relaunched process is out of `Neuron`'s control. Currently, the `ckb` variable is null, but the `ckb` is running. So we can't restart `ckb` node anymore. I will try to find out why the `ckb` process closed with 101.

Recently I received a report that CKB kept running after Neuron had been shut down, possibly caused by this case.

**Comment by yanguoyu** [comment] 2023-01-17 07:54
> Recently I received a report that CKB kept running after Neuron had been shut down, possibly caused by this case.

Maybe or not, because after I use `cmd` + c to close `Neuron`, the `CKB` will also shut down.
Maybe it will be closed because of `electron` will close all processes when clicking `cmd` + c.

**Comment by yanguoyu** [comment] 2023-01-17 09:19
> > Recently I received a report that CKB kept running after Neuron had been shut down, possibly caused by this case.
> 
> Maybe or not, because after I use `cmd` + c to close `Neuron`, the `CKB` will also shut down. Maybe it will be closed because of `electron` will close all processes when clicking `cmd` + c.

It possibly caused by this case, electron API `app.quit` will not close related processes but `cmd` + C will close all related processes.

**Comment by yanguoyu** [comment] 2023-01-18 01:32
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/12881040/213058955-340d3613-e4e3-401a-8f86-1e67d7db44a8.png">
<img width="817" alt="image" src="https://user-images.githubusercontent.com/12881040/213059013-3ffab7b3-5a98-46dd-adb1-fe8f1a8cb753.png">
From these two pictures, the 101 exit code may be caused by `ckb`, I will confirm these things with the core team later.

**Comment by yanguoyu** [comment] 2023-01-18 03:05
<img width="761" alt="image" src="https://user-images.githubusercontent.com/12881040/213071871-4667bb47-0118-4b34-84e1-aa62b1367408.png">
I think it may be caused by we want to start two `ckb` processes causing the `ckb` throw 101 code. It may happen when there is no response from `ckb` RPC, but the `ckb` is not closed. So I will add try to call `stopCkbNode` when the ckb variable is not null before startCkbNode.

**Comment by yanguoyu** [comment] 2023-01-18 07:54
https://github.com/nervosnetwork/neuron/pull/2574

**Comment by Cedar67** [comment] 2023-01-19 15:38
> [nervosnetwork/neuron#2574](https://github.com/nervosnetwork/neuron/pull/2574)

Verified.

**Closed** 2023-06-13 01:28 UTC
Labels: bug
