### ISSUE TITLE
Nervos Dao deposit locked time shows abnormal

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#236] opened 2023-07-25 09:12 UTC
In deposit records page，locked time shows 0，but when unlocked it shows 42 days.

https://github.com/Magickbase/neuron-public-issues/assets/25971273/203a0484-454f-46f0-aa84-4254434980df

**Comment by yanguoyu** [comment] 2023-07-28 03:24
It's not a bug, the `Compensated Period` shown on `Deposits` page means `lock time`.(Withdraw Epoch(If not withdrawn use Current Epoch) -  Deposit Epoch). So this value will equal the `Compensation Period` on `Completed` page.
The English is clear, you can switch to English.

**Comment by silySuper** [comment] 2023-07-28 08:22
You mean that the meaning of ‘已锁定时间 '  in deposit page is equal to ‘补贴时间’ in unlock page，not is equal to '锁定时间'?Maybe the Chinese language mislead me.Can we adjust the Chinese name？ @Danie0918 @yanguoyu

**Comment by yanguoyu** [comment] 2023-07-28 08:30
> You mean that the meaning of ‘已锁定时间 ' in deposit page is equal to ‘补贴时间’ in unlock page，not is equal to '锁定时间'?Maybe the Chinese language mislead me.Can we adjust the Chinese name？ @Danie0918 @yanguoyu

When the DAO is not withdrawn, it means `锁定时间`, otherwise it means `补贴时间`. Because after withdrawal, the interest has been determined.

**Comment by silySuper** [comment] 2023-07-28 08:52
Because I think withrdraw time-deposit time=compensation period（补偿时间）
unlock time-deposit time=locked period（锁定时间）
deposit page only can show compensation period,locked period shows in complete page.
So I think change '已锁定时间' in deposit page  to '补偿时间' in Chinese language is better.

**Comment by yanguoyu** [comment] 2023-07-29 02:44
> Because I think withrdraw time-deposit time=compensation period（补偿时间） unlock time-deposit time=locked period（锁定时间） deposit page only can show compensation period,locked period shows in complete page. So I think change '已锁定时间' in deposit page to '补偿时间' in Chinese language is better.

A good suggestion. It's more clear for users. I don't know why use `锁定时间` for the first step withdrawn DAO before.
But the English translation is `Compensated Period`. Is it a faulty translation? @Keith-CY 
<img width="665" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/b4ec2380-57ae-4660-9fd2-644334a5a811">
<img width="469" alt="image" src="https://github.com/Magickbase/neuron-public-issues/assets/12881040/8fb2e198-ffba-4ad1-979e-22f29bbbde72">

**Comment by Keith-CY** [comment] 2023-07-31 03:59
> > Because I think withrdraw time-deposit time=compensation period（补偿时间） unlock time-deposit time=locked period（锁定时间） deposit page only can show compensation period,locked period shows in complete page. So I think change '已锁定时间' in deposit page to '补偿时间' in Chinese language is better.
> 
> A good suggestion. It's more clear for users. I don't know why use `锁定时间` for the first step withdrawn DAO before. But the English translation is `Compensated Period`. Is it a faulty translation? @Keith-CY <img alt="image" width="665" src="https://user-images.githubusercontent.com/12881040/256959645-b4ec2380-57ae-4660-9fd2-644334a5a811.png"> <img alt="image" width="469" src="https://user-images.githubusercontent.com/12881040/256959684-8fb2e198-ffba-4ad1-979e-22f29bbbde72.png">

I cannot find the original PRD, but `已补偿时间` is clearer than `已锁定时间`

**Comment by yanguoyu** [comment] 2023-08-07 02:11
Fixed by https://github.com/nervosnetwork/neuron/pull/2795

**Closed** 2024-04-29 08:17 UTC
Labels: bug
